### ISSUE TITLE
Close the plyer after finishing the video

### ISSUE THREAD

**Issue by BogdanJak** [frankhale/toby-blazor#11]
Hi 
How to automatically close the player window after the video ends?

Regards
Bogdan

**Comment by frankhale** [comment]
Just added this. Also upgraded to .NET 8.

**Comment by BogdanJak** [comment]
I'm trying to create my own Youtube player example based on your code. But unfortunately I'm stuck. The link below is my Github repository.
https://github.com/BogdanJak/ModalBlazorX
Can you check what I'm doing wrong?

Regards
Bogdan

**Comment by frankhale** [comment]
I will take a look.

**Comment by frankhale** [comment]
As a first step are you trying to create a component that plays a YouTube
video? I see a bunch of issues with the current code which is why it does
not work.

**Comment by BogdanJak** [comment]
Beginnings are always difficult

**Comment by frankhale** [comment]
No worries. The important thing is that the YouTube API has to be
initialized, this has to be done in JavaScript before a Blazor component
can use it. Once the YouTube API is initialized and ready then a video can
be played.

Start here, once you can get the example running then it should be fairly
easy to get something working in Blazor:

https://developers.google.com/youtube/iframe_api_reference

That documentation has a complete and very simple working example of how to
embed a YouTube video into a webpage. This is the core aspect of what I'm
doing. The only difference between that simple example is that I'm adding a
SQLite database and a few other features to save and search.

Let me know how you get on with that and if you need more help please let
me know.

**Comment by BogdanJak** [comment]
In another application, the Youtube player works fine - but bypassing the modal window.
However, in my code sample I have a problem opening the VideoPopup.razor modal window.
Since Java is "black magic" for me, I asked for help in opening a modal window.

**Comment by BogdanJak** [comment]
Hi

1. Attached is a video of the error I get when trying to play the same video clip again. I don't know why this happens.
2. You can add to your application the ability to play all your favorite video clips in turn (without having to click individual clips - one button play all)

regards
Bogdan

https://github.com/frankhale/toby-blazor/assets/54505464/a9b376ef-d9ac-4e9e-a2de-21beb84cd584

**Comment by frankhale** [comment]
I suspect that there are some issues with how the YouTube iframe API is being used. It's quite possible that some of the state of the YouTube API is being corrupted by accident due to probably errors on my part and the fact that the Blazor app was recently upgraded to .NET 8. Also this code is showing it's age especially the dirty JavaScript that is using jQuery. 

This code attempts to initialize the YouTube API once and then reuse it. I think a better solution would be to load a fresh YouTube API on every video popup so that there is no way to corrupt the state of the player.
