### ISSUE TITLE
YouTube Player Error when quickly switching videos

### ISSUE THREAD

**Issue by frankhale** [frankhale/toby-blazor#12]
Hi

1. Attached is a video of the error I get when trying to play the same video clip again. I don't know why this happens.
2. You can add to your application the ability to play all your favorite video clips in turn (without having to click individual clips - one button play all)

regards
Bogdan

https://github.com/frankhale/toby-blazor/assets/54505464/a9b376ef-d9ac-4e9e-a2de-21beb84cd584

_Originally posted by @BogdanJak in https://github.com/frankhale/toby-blazor/issues/11#issuecomment-2156138218_

**Comment by frankhale** [comment]
I suspect that there are some issues with how the YouTube iframe API is being used. It's quite possible that some of the state of the YouTube API is being corrupted by accident due to probably errors on my part and the fact that the Blazor app was recently upgraded to .NET 8. Also this code is showing it's age especially the dirty JavaScript that is using jQuery.

This code attempts to initialize the YouTube API once and then reuse it. I think a better solution would be to load a fresh YouTube API on every video popup so that there is no way to corrupt the state of the player.

**Comment by BogdanJak** [comment]
Hi

Do you already have an idea how to solve this problem?

**Comment by frankhale** [comment]
Yes, have a look at the last message I posted (right above yours). 

> This code attempts to initialize the YouTube API once and then reuse it. I think a better solution would be to load a fresh YouTube API on every video popup so that there is no way to corrupt the state of the player.

**Comment by frankhale** [comment]
There are a few things that I think need done. 

- I don't trust the Blazor upgrade so first step would be to rewrite in a clean new Blazor project
- In the YouTube player component initialize the YouTube API each time it's used so there is no chance to corrupt the player by switching videos. The current code tries to reuse the YouTube API by initializing it once and this may be causing the issues seen.
- Refactor other components to make them nicer
- Remove legacy jQuery code

**Comment by BogdanJak** [comment]
Hi
I have a request.
Attached is a sample of my code in which I'm trying to play a list of several video clips in a queue - one by one. (This part works fine). The first clip plays correctly, the dialog closes, after opening the second dialog there is a problem with loading the Youtube api.
Since I have no experience with java code - I don't even know where to start to implement what you wrote in the message above.

That's why I'm asking for help.

[YoutubePlayer1.zip](https://github.com/user-attachments/files/15900984/YoutubePlayer1.zip)

**Comment by frankhale** [comment]
Your request is what discovered the issue. A slight redesign should make the problem go away. Instead of initializing the YouTube Iframe API once and trying to reuse it, a different approach would be to initialize the YouTube Iframe API for each popup ensuring there is no possibility to corrupt (and I use that term very loosely because I don't exactly know what's going on) the state of the YouTube player. Back when I started this there were no issues like this because I used to use this player extensively. All I can say is that the YouTube Iframe API has probably changed and combined with how I am using it results in weird states that the player complains about and manifests the issue that has been reported.

**Comment by frankhale** [comment]
I'm looking at making the changes I discussed in earlier messages. I cannot provide a timeline though.

**Comment by frankhale** [comment]
I think I solved this with the latest commit

**Comment by BogdanJak** [comment]
Thank you for your help. Good job. Everything works as I wanted.
